### ISSUE TITLE
Missing SLE modules

### ISSUE THREAD

**Issue by vijaigan** [stdevel/ansible-uyuni#22]
Hi 

I have tried installing the SUSE Manager 4.0 using the Ansible. 
Encountered error during the installation and found the modules needs to be updated with the following order. 
requesting you to kindly update the code base with the changes.

```
sles_modules:

  - name: sle-module-basesystem
    identifier: sle-module-basesystem/15.1/x86_64
  - name: sle-module-web-scripting
    identifier: sle-module-web-scripting/15.1/x86_64
  - name: sle-module-python2
    identifier: sle-module-python2/15.1/x86_64
  - name: sle-module-suse-manager-server
    identifier: sle-module-suse-manager-server/4.0/x86_64
  - name: sle-module-server-applications
    identifier: sle-module-server-applications/15.1/x86_64
  - name: sle-module-desktop-applications
    identifier: sle-module-desktop-applications/15.1/x86_64
  - name: sle-module-development-tools
    identifier: sle-module-development-tools/15.1/x86_64
```
