### ISSUE TITLE
Add variable to change size of lv and filesystem 

### ISSUE THREAD

**Issue by ALutz273** [stdevel/ansible-uyuni#32]
create a variable to change the default fs size of 10GB for production systems.
this has been noticed during an installation. 
Is this a good idea?

**Comment by stdevel** [comment]
Hi @ALutz273,
currently there are the following variables for this:

```yaml
uyuni_use_lvm: true
uyuni_vg: vg_uyuni
uyuni_pv: /dev/sdb
uyuni_filesystems:
  - name: lv_uyuni
    type: xfs
    mountpoint: /var/spacewalk
    size: 10240
  - name: lv_pgsql
    type: xfs
    mountpoint: /var/lib/pgsql
    size: 10240
```

So you can easily adjust the filesystem sizes.

Does this help you?

Best wishes,
Christian.
